### ISSUE TITLE
CalculiX Segmentation Fault on using USER Material

### ISSUE THREAD

**Issue by bhanups1991** [calculix/examples#1]
Any idea about segmentation fault??

I get this error when I try to run a static analysis. I am using a USER defined UMAT (elasto-plastic). I suspect that the error is because of this UMAT only because without it there's no segmentation fault whatever.

Just for information, I have taken this UMAT code from ABAQUS documentation (file-name: cylbillet_slow_usr_umat_umatht.f) so I don't think there's any error inside the UMAT code as such. Or maybe it is. Comments??

CalculiX documentation does give some hits on searching ''segmentation fault" but none are linked/related to the use of UMAT (at least that is what I gathered).

Can anyone help?

**Comment by imirzov** [comment]
You'd better ask for help here:
https://calculix.discourse.group/
