### ISSUE TITLE
Nastran examples with theory

### ISSUE THREAD

**Issue by stefano2734** [calculix/examples#2]
perhaps a source for new examples:

see
https://www.autodesk.com/sites/default/files/file_downloads/Autodesk-Inventor-Nastran-2022-Verification-Manual.pdf
and or 
https://docs.plm.automation.siemens.com/data_services/resources/scnastran/2020_1/help/tdoc/en_US/pdf/verification.pdf
and or 
https://help-be.hexagonmi.com/bundle/MSC_Nastran_2021.2_Verification_Guide/raw/resource/enus/MSC_Nastran_2021.2_Verification_Guide.pdf?save_local=true

Autodesk Nastran 2023: https://help.autodesk.com/view/NINCAD/2023/ENU/?caas=caas/downloads/content/autodesk-inventor-nastran-2023-offline-help.html

COMSOL: https://doc.comsol.com/5.5/doc/com.comsol.help.sme/StructuralMechanicsVerificationExamples.pdf

Code Aster:
https://code-aster.org/doc/default/en/index.php?man=cas-test

**Comment by stefano2734** [comment]
There are also possible more of abaqus examples in a short way to calculix.

Older with more compatibility:
https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/ver/default.htm?startat=ami01.html


and new Abaqus 2022:
https://docs.software.vt.edu/abaqusv2022/English/?show=SIMACAEEXARefMap/simaexa-c-ov.htm

But this is work, mostly for students with available abaqus academic version in learning FEA.

**Comment by imirzov** [comment]
This is not an issue. If you wish to add some examples to the repository - why you didn't do that?
For blog posts use https://calculix.discourse.group/
